---
include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - packages/**
strong-mode:
  implicit-dynamic: true

linter:
  rules:
    avoid_print: false
    avoid_setters_without_getters: false
    always_use_package_imports: false
    public_member_api_docs: false
    prefer_relative_imports: true
    prefer_void_to_null: true
    one_member_abstracts: false
